name: Build and deploy Python project to Azure Function App - dlp-redact-resend-func

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create clean deployment package
        run: |
          mkdir deploy
          
          # Create a minimal function_app.py
          cat > deploy/function_app.py << 'EOF'
          import azure.functions as func
          import json
          import logging

          app = func.FunctionApp(http_auth_level=func.AuthLevel.FUNCTION)

          @app.route(route="redact_resend")
          async def redact_resend(req: func.HttpRequest) -> func.HttpResponse:
              logging.info('Python HTTP trigger function processed a request.')
              
              try:
                  body = {"status": "resent", "messageId": "dummy-id"}
                  return func.HttpResponse(
                      json.dumps(body),
                      status_code=200,
                      mimetype="application/json"
                  )
              except Exception as e:
                  logging.error(f"Error: {str(e)}")
                  return func.HttpResponse(
                      json.dumps({"error": "Request failed"}),
                      status_code=500,
                      mimetype="application/json"
                  )
          EOF
          
          # Create host.json
          cat > deploy/host.json << 'EOF'
          {
            "version": "2.0",
            "logging": {
              "applicationInsights": {
                "samplingSettings": {
                  "isEnabled": true,
                  "excludedTypes": "Request"
                }
              }
            },
            "extensionBundle": {
              "id": "Microsoft.Azure.Functions.ExtensionBundle",
              "version": "[4.*, 5.0.0)"
            },
            "functionTimeout": "00:05:00"
          }
          EOF
          
          # Create requirements.txt
          cat > deploy/requirements.txt << 'EOF'
          azure-functions>=1.18.0
          EOF

      - name: Debug package
        run: |
          echo "=== Package Structure ==="
          find deploy -type f -exec ls -la {} \;
          echo "=== function_app.py ==="
          cat deploy/function_app.py
          echo "=== host.json ==="
          cat deploy/host.json

      - name: Azure Login
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9DFF1B7D3671481E9B08BA3B92D48BA3 }}

      - name: Deploy to Azure Functions
        run: |
          cd deploy
          zip -r ../deploy.zip .
          cd ..
          
          # Try to get resource group from az cli
          RESOURCE_GROUP=$(az functionapp show --name dlp-redact-resend-func --query resourceGroup -o tsv 2>/dev/null || echo "")
          
          if [ -n "$RESOURCE_GROUP" ]; then
            echo "Found resource group: $RESOURCE_GROUP"
            az functionapp deployment source config-zip \
              --resource-group "$RESOURCE_GROUP" \
              --name dlp-redact-resend-func \
              --src deploy.zip \
              --verbose
          else
            echo "Could not find resource group, trying without it..."
            az functionapp deployment source config-zip \
              --name dlp-redact-resend-func \
              --src deploy.zip \
              --verbose
          fi
          
