name: Deploy with Azure CLI

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'
  AZURE_FUNCTIONAPP_NAME: 'dlp-redact-resend-func'
  AZURE_RESOURCE_GROUP: 'rg-dlp-automation'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create deployment package
        run: |
          mkdir package
          
          # Create function_app.py
          cat > package/function_app.py << 'EOF'
          import azure.functions as func
          import json
          import logging

          app = func.FunctionApp(http_auth_level=func.AuthLevel.FUNCTION)

          @app.route(route="redact_resend")
          async def redact_resend(req: func.HttpRequest) -> func.HttpResponse:
              logging.info('Python HTTP trigger function processed a request.')
              body = {"status": "resent", "messageId": "dummy-id"}
              return func.HttpResponse(
                  json.dumps(body),
                  status_code=200,
                  mimetype="application/json"
              )
          EOF
          
          # Create host.json
          cp host.json package/ || cat > package/host.json << 'EOF'
          {
            "version": "2.0",
            "extensionBundle": {
              "id": "Microsoft.Azure.Functions.ExtensionBundle",
              "version": "[4.*, 5.0.0)"
            }
          }
          EOF
          
          # Create requirements.txt
          echo "azure-functions" > package/requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9DFF1B7D3671481E9B08BA3B92D48BA3 }}

      - name: Deploy to Azure Functions
        run: |
          cd package
          zip -r ../deploy.zip .
          cd ..
          
          az functionapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src deploy.zip \
            --build-remote false \
            --verbose
            
