name: Build and deploy Python project to Azure Function App - dlp-redact-resend-func

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './package'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Debug - List current directory contents
        run: |
          echo "Repository contents:"
          ls -la
          echo "Repository structure:"
          find . -type f -name "*.py" -o -name "*.json" -o -name "*.txt"

      - name: Create package directory
        run: mkdir -p ./package

      - name: Install dependencies to package directory
        run: |
          pip install --target ./package -r requirements.txt

      - name: Copy function files to package
        run: |
          cp function_app.py ./package/
          cp host.json ./package/
          cp requirements.txt ./package/
          if [ -d "redact_resend" ]; then
            cp -r redact_resend ./package/
          fi

      - name: Debug - List package contents
        run: |
          echo "Package contents:"
          ls -la ./package/
          echo "Package structure:"
          find ./package -type f | head -30
          echo "Package size:"
          du -sh ./package/

      - name: Validate package structure
        run: |
          echo "Checking for required files:"
          echo "function_app.py exists: $(test -f ./package/function_app.py && echo 'YES' || echo 'NO')"
          echo "host.json exists: $(test -f ./package/host.json && echo 'YES' || echo 'NO')"
          echo "requirements.txt exists: $(test -f ./package/requirements.txt && echo 'YES' || echo 'NO')"
          
          echo "Checking file contents:"
          echo "=== function_app.py ===" 
          head -5 ./package/function_app.py
          echo "=== host.json ==="
          cat ./package/host.json

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'dlp-redact-resend-func'
          slot-name: 'production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9DFF1B7D3671481E9B08BA3B92D48BA3 }}
          scm-do-build-during-deployment: false
          enable-oryx-build: false
          remote-build: false
          
